import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { getUser, jsonError } from "@/lib/api";
import { hashPassword } from "@/lib/password";
import { z } from "zod";
const schema = z.object({ id: z.string().optional(), name: z.string().min(2), telegramId: z.string().regex(/^\d+$/, "Telegram ID должен содержать только цифры").optional().or(z.literal("")), phone: z.string().optional(), email: z.string().email().optional().or(z.literal("")), password: z.string().min(6).optional(), commissionPercent: z.coerce.number().min(0).max(100).default(0), role: z.enum(["ADMIN", "MANAGER", "ACCOUNTANT"]).default("MANAGER"), permissions: z.record(z.boolean()).default({}) });
export async function GET(request: NextRequest) { try { const user = await getUser(request); const rows = await prisma.teamMember.findMany({ where: { ownerId: user.id }, orderBy: { name: "asc" } }); return Response.json(rows.map(row => ({ id: row.id, name: row.name, telegramId: row.telegramId?.toString() ?? "", phone: row.phone, email: row.email, commissionPercent: Number(row.commissionPercent), role: row.role, active: row.active }))); } catch (e) { return jsonError(e, 401); } }
export async function POST(request: NextRequest) { try { const user = await getUser(request); if (user.role !== "OWNER" && user.role !== "ADMIN") throw new Error("Только OWNER или ADMIN может управлять командой"); const data = schema.parse(await request.json()); const telegramId = data.telegramId === "" || data.telegramId == null ? null : BigInt(data.telegramId); if (!data.password) throw new Error("Пароль обязателен"); const passwordHash = hashPassword(data.password); const payload = { ownerId: user.id, name: data.name, telegramId, phone: data.phone || null, email: data.email ? data.email.toLowerCase() : null, passwordHash, commissionPercent: data.commissionPercent, role: data.role, permissions: data.permissions, active: true }; const existing = telegramId ? await prisma.teamMember.findUnique({ where: { telegramId } }) : null; const result = existing ? await prisma.teamMember.update({ where: { id: existing.id }, data: payload }) : await prisma.teamMember.create({ data: payload }); return Response.json({ id: result.id, name: result.name, role: result.role, commissionPercent: Number(result.commissionPercent) }, { status: 201 }); } catch (e) { return jsonError(e); } }
export async function PATCH(request: NextRequest) { try { const user = await getUser(request); if (user.role !== "OWNER" && user.role !== "ADMIN") throw new Error("Недостаточно прав"); const body = schema.parse(await request.json()); if (!body.id) throw new Error("Не указан менеджер"); const data: Record<string, unknown> = { name: body.name, telegramId: body.telegramId ? BigInt(body.telegramId) : null, phone: body.phone || null, email: body.email ? body.email.toLowerCase() : null, commissionPercent: body.commissionPercent, role: body.role }; if (body.password) data.passwordHash = hashPassword(body.password); await prisma.teamMember.updateMany({ where: { id: body.id, ownerId: user.id }, data }); return Response.json({ ok: true }); } catch (e) { return jsonError(e); } }
export async function DELETE(request: NextRequest) { try { const user = await getUser(request); if (user.role !== "OWNER" && user.role !== "ADMIN") throw new Error("Недостаточно прав"); const id = String((await request.json()).id); await prisma.teamMember.deleteMany({ where: { id, ownerId: user.id } }); return Response.json({ ok: true }); } catch (e) { return jsonError(e); } }
