"use client";
import { useEffect, useRef, useState } from "react";

const CONSENT_TEXT = "Я подтверждаю, что получил(а) информацию об аренде, прочитал(а) акт передачи и условия аренды, согласен(на) с указанными суммой, сроком, депозитом и обязанностями клиента. Подтверждаю, что сведения в акте верны.";

export default function ActActions({ token, status, acceptedAt, acceptedName }: { token: string; status: string; acceptedAt: string | null; acceptedName?: string | null }) {
  const [name, setName] = useState(acceptedName || ""); const [message, setMessage] = useState(""); const [accepted, setAccepted] = useState(status === "ACCEPTED"); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const canvasRef = useRef<HTMLCanvasElement | null>(null); const drawing = useRef(false); const hasSignature = useRef(false);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const resize = () => { const ratio = Math.max(1, window.devicePixelRatio || 1); const rect = canvas.getBoundingClientRect(); canvas.width = Math.max(1, Math.floor(rect.width * ratio)); canvas.height = Math.max(1, Math.floor(rect.height * ratio)); const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.scale(ratio, ratio); ctx.lineWidth = 2.2; ctx.lineCap = "round"; ctx.lineJoin = "round"; ctx.strokeStyle = "#17394d"; }; resize(); window.addEventListener("resize", resize); return () => window.removeEventListener("resize", resize); }, []);
  const point = (event: React.PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; };
  const start = (event: React.PointerEvent<HTMLCanvasElement>) => { event.currentTarget.setPointerCapture(event.pointerId); const ctx = event.currentTarget.getContext("2d"); if (!ctx) return; const p = point(event); ctx.beginPath(); ctx.moveTo(p.x, p.y); drawing.current = true; hasSignature.current = true; };
  const move = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!drawing.current) return; const ctx = event.currentTarget.getContext("2d"); if (!ctx) return; const p = point(event); ctx.lineTo(p.x, p.y); ctx.stroke(); };
  const end = () => { drawing.current = false; };
  const clear = () => { const canvas = canvasRef.current; const ctx = canvas?.getContext("2d"); if (canvas && ctx) ctx.clearRect(0, 0, canvas.width, canvas.height); hasSignature.current = false; };
  const share = async () => { try { if (navigator.share) await navigator.share({ title: "Акт передачи RideFlow Rent", url: window.location.href }); else { await navigator.clipboard.writeText(window.location.href); setMessage("Ссылка скопирована"); } } catch { setMessage("Поделиться отменено"); } };
  const accept = async () => { if (name.trim().length < 2) { setMessage("Укажите имя или ФИО"); return; } if (!consent) { setMessage("Поставьте отметку согласия с актом и условиями аренды"); return; } const canvas = canvasRef.current; if (!canvas || !hasSignature.current) { setMessage("Поставьте подпись пальцем в поле выше"); return; } setBusy(true); try { const response = await fetch(`/api/acts/public/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, consent, consentText: CONSENT_TEXT, signature: canvas.toDataURL("image/png") }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Не удалось подтвердить акт"); setAccepted(true); setMessage("Акт принят и подписан. Спасибо."); } catch (error) { setMessage(error instanceof Error ? error.message : "Не удалось подтвердить акт"); } finally { setBusy(false); } };
  const currentUrl = typeof window !== "undefined" ? window.location.href : ""; const telegramUrl = `https://t.me/share/url?url=${encodeURIComponent(currentUrl)}&text=${encodeURIComponent("Акт передачи RideFlow Rent")}`; const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(`Акт передачи RideFlow Rent: ${currentUrl}`)}`;
  return <div className="actActions"><button type="button" className="actCloseButton" onClick={() => { if (window.history.length > 1) window.history.back(); else window.location.href = "/"; }} aria-label="Закрыть акт">×</button><div className="actShareRow"><button onClick={() => window.print()} className="actPrimaryButton">Сохранить PDF / печать</button><button onClick={share} className="actSecondaryButton">Поделиться</button></div>{accepted ? <div className="actAccepted"><b>✓ Акт уже принят и подписан</b><span>{acceptedName || name}{acceptedAt ? ` · ${new Date(acceptedAt).toLocaleString("ru-RU")}` : ""}</span></div> : <div className="actAcceptBox"><b>Подтверждение и подпись клиента</b><p>{CONSENT_TEXT}</p><label className="actConsent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} /> <span>Я согласен(на) с актом и условиями аренды</span></label><div className="actSignatureHead"><span>Подпись пальцем по экрану</span><button type="button" onClick={clear} className="actClearSignature">Очистить</button></div><canvas ref={canvasRef} className="actSignatureCanvas" onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onPointerLeave={end} /><input value={name} onChange={e => setName(e.target.value)} placeholder="Имя или ФИО гостя" autoComplete="name" /><button onClick={accept} disabled={busy} className="actAcceptButton">{busy ? "Сохраняем…" : "Соглашаюсь и подписываю акт"}</button></div>}<div className="actGuestShare"><button onClick={async () => { await navigator.clipboard?.writeText(window.location.href); setMessage("Ссылка скопирована"); }}>Копировать ссылку</button><a href={telegramUrl}>Telegram</a><a href={whatsappUrl} target="_blank" rel="noreferrer">WhatsApp</a></div>{message && <small className="actActionMessage">{message}</small>}</div>;
}
