"use client";
import { useState } from "react";
export default function ActActions({ token, status, acceptedAt, acceptedName }: { token: string; status: string; acceptedAt: string | null; acceptedName?: string | null }) {
  const [name, setName] = useState(acceptedName || ""); const [message, setMessage] = useState(""); const [accepted, setAccepted] = useState(status === "ACCEPTED"); const [busy, setBusy] = useState(false);
  const share = async () => { try { if (navigator.share) await navigator.share({ title: "Акт передачи RideFlow Rent", url: window.location.href }); else { await navigator.clipboard.writeText(window.location.href); setMessage("Ссылка скопирована"); } } catch { setMessage("Поделиться отменено"); } };
  const accept = async () => { if (name.trim().length < 2) { setMessage("Укажите имя или ФИО"); return; } setBusy(true); try { const response = await fetch(`/api/acts/public/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Не удалось подтвердить акт"); setAccepted(true); setMessage("Акт принят. Спасибо."); } catch (error) { setMessage(error instanceof Error ? error.message : "Не удалось подтвердить акт"); } finally { setBusy(false); } };
  const currentUrl = typeof window !== "undefined" ? window.location.href : "";
  const telegramUrl = `https://t.me/share/url?url=${encodeURIComponent(currentUrl)}&text=${encodeURIComponent("Акт передачи RideFlow Rent")}`;
  const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(`Акт передачи RideFlow Rent: ${currentUrl}`)}`;
  return <div className="actActions"><div className="actShareRow"><button onClick={() => window.print()} className="actPrimaryButton">Сохранить PDF / печать</button><button onClick={share} className="actSecondaryButton">Поделиться</button></div>{accepted ? <div className="actAccepted"><b>✓ Акт уже принят</b><span>{acceptedName || name}{acceptedAt ? ` · ${new Date(acceptedAt).toLocaleString("ru-RU")}` : ""}</span></div> : <div className="actAcceptBox"><b>Удалённое подтверждение</b><p>Прочитайте акт и условия аренды. Введите имя или ФИО и подтвердите ознакомление.</p><input value={name} onChange={e => setName(e.target.value)} placeholder="Имя или ФИО гостя" autoComplete="name" /><button onClick={accept} disabled={busy} className="actAcceptButton">{busy ? "Сохраняем…" : "Я ознакомлен и принимаю"}</button></div>}<div className="actGuestShare"><button onClick={async () => { await navigator.clipboard?.writeText(window.location.href); setMessage("Ссылка скопирована"); }}>Копировать ссылку</button><a href={telegramUrl}>Telegram</a><a href={whatsappUrl} target="_blank" rel="noreferrer">WhatsApp</a></div>{message && <small className="actActionMessage">{message}</small>}</div>;
}
