import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { getAccess, jsonError } from "@/lib/api";
import { addDays, differenceInCalendarDays, startOfDay } from "date-fns";
export async function GET(request: NextRequest) {
  try {
    const { user, member } = await getAccess(request);
    const today = startOfDay(new Date()); const monthStart = new Date(today.getFullYear(), today.getMonth(), 1); const monthEnd = new Date(today.getFullYear(), today.getMonth() + 1, 1); const monthDays = differenceInCalendarDays(monthEnd, monthStart); const tomorrow = addDays(today, 1); const week = addDays(today, 7);
    const [bookings, payments, expenses, assets, blocks, team, branches] = await Promise.all([
      prisma.booking.findMany({ where: { userId: user.id, status: { notIn: ["CANCELLED"] } }, include: { asset: true, partner: true }, orderBy: { startDate: "asc" } }),
      prisma.payment.findMany({ where: { userId: user.id } }), prisma.expense.findMany({ where: { userId: user.id }, include: { asset: true } }), prisma.asset.findMany({ where: { userId: user.id }, include: { branch: true }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }), prisma.assetBlock.findMany({ where: { userId: user.id } }), prisma.teamMember.findMany({ where: { ownerId: user.id, active: true }, select: { commissionPercent: true } }), prisma.branch.findMany({ where: { userId: user.id }, orderBy: { createdAt: "asc" } })
    ]);
    const money = (v: unknown) => Number(v); const percent = member ? Number(member.commissionPercent) : 0; const manager = Boolean(member);
    const rentalDays = bookings.reduce((sum, b) => sum + Math.max(0, differenceInCalendarDays(b.endDate, b.startDate)), 0); const rentalPayments = payments.filter(p => p.paymentType === "RENTAL"); const depositPayments = payments.filter(p => p.paymentType === "DEPOSIT"); const depositReturns = payments.filter(p => p.paymentType === "DEPOSIT_RETURN"); const rentalByBooking = new Map<string, number>(); rentalPayments.forEach(p => { if (p.bookingId) rentalByBooking.set(p.bookingId, (rentalByBooking.get(p.bookingId) || 0) + money(p.amount)); }); const depositByBooking = new Map<string, number>(); depositPayments.forEach(p => { if (p.bookingId) depositByBooking.set(p.bookingId, (depositByBooking.get(p.bookingId) || 0) + money(p.amount)); }); const recordedBookingIds = new Set(rentalPayments.map(p => p.bookingId).filter(Boolean)); const grossRevenue = rentalPayments.reduce((sum, p) => sum + money(p.amount), 0) + bookings.filter(b => Number(b.paidAmount) > 0 && !recordedBookingIds.has(b.id)).reduce((sum, b) => sum + Math.max(0, money(b.paidAmount) - (depositByBooking.get(b.id) || 0)), 0); const commission = grossRevenue * percent / 100; const deposits = Math.max(0, depositPayments.reduce((sum, p) => sum + money(p.amount), 0) - depositReturns.reduce((sum, p) => sum + money(p.amount), 0)); const expensesTotal = expenses.reduce((sum, e) => sum + money(e.amount), 0); const expected = bookings.reduce((sum, b) => { const paidForRental = rentalByBooking.has(b.id) ? (rentalByBooking.get(b.id) || 0) : Math.max(0, money(b.paidAmount) - (depositByBooking.get(b.id) || 0)); return sum + Math.max(0, money(b.totalPrice) - paidForRental); }, 0);
    const paidForRental = (booking: { id: string; paidAmount: unknown }) => rentalByBooking.has(booking.id) ? (rentalByBooking.get(booking.id) || 0) : Math.max(0, money(booking.paidAmount) - (depositByBooking.get(booking.id) || 0)); const statusLabel = (status: string) => ({ PENDING: "Ожидает подтверждения", CONFIRMED: "Подтверждена", PAID: "Оплачена", ACTIVE: "В аренде", COMPLETED: "Завершена", CANCELLED: "Отменена" } as Record<string, string>)[status] || status; const todayReturns = bookings.filter(b => b.endDate >= today && b.endDate < tomorrow).map(b => ({ id: b.id, clientName: b.clientName, assetName: b.asset.name, time: b.endDate.toISOString(), status: b.status, statusLabel: statusLabel(b.status) })); const todayPickups = bookings.filter(b => b.startDate >= today && b.startDate < tomorrow).map(b => ({ id: b.id, clientName: b.clientName, assetName: b.asset.name, time: b.startDate.toISOString(), status: b.status, statusLabel: statusLabel(b.status) })); const upcomingPayments = bookings.filter(b => !["CANCELLED", "COMPLETED", "PAID"].includes(b.status) && (b.endDate >= today && b.startDate <= week || Number(b.extensionAmount || 0) > 0) && money(b.totalPrice) - paidForRental(b) > 0).map(b => ({ id: b.id, clientName: b.clientName, assetName: b.asset.name, amount: Math.max(0, money(b.totalPrice) - paidForRental(b)), date: b.startDate.toISOString(), status: b.status, statusLabel: "Ожидает оплаты" }));
    const serviceAssets = assets.filter(a => { const mileage = a.currentMileage ?? 0; return a.status === "MAINTENANCE" || (a.serviceMileage != null && mileage >= a.serviceMileage) || (a.oilChangeMileage != null && mileage >= a.oilChangeMileage) || (a.variatorServiceMileage != null && mileage >= a.variatorServiceMileage); }).map(a => ({ id: a.id, name: a.name, status: a.status, currentMileage: a.currentMileage, serviceMileage: a.serviceMileage, oilChangeMileage: a.oilChangeMileage, variatorServiceMileage: a.variatorServiceMileage, lastServiceDate: a.lastServiceDate, serviceNote: a.serviceNote || [a.oilChangeMileage ? `масло: ${a.oilChangeMileage}` : "", a.variatorServiceMileage ? `вариатор: ${a.variatorServiceMileage}` : ""].filter(Boolean).join(" · ") }));
    const partnerCommission = bookings.reduce((sum, b) => { if (!b.partner || b.partner.commissionType !== "PERCENT") return sum; const paid = paidForRental(b); return sum + Math.max(0, paid - Number(b.extensionAmount || 0)) * Number(b.partner.commissionValue) / 100; }, 0);
    const configuredManagerPercent = team.reduce((max, item) => Math.max(max, Number(item.commissionPercent)), 0);
    const managerCommission = manager ? commission : grossRevenue * configuredManagerPercent / 100;
    const branchRows = branches.map(branch => { const branchAssets = assets.filter(asset => asset.branchId === branch.id); const branchIncome = branchAssets.reduce((sum, asset) => sum + bookings.filter(b => b.assetId === asset.id).reduce((inner, b) => inner + paidForRental(b), 0), 0); const branchExpenses = expenses.filter(expense => expense.branchId === branch.id).reduce((sum, expense) => sum + money(expense.amount), 0); const branchCommission = branchIncome * Number(branch.commissionPercent) / 100; return { id: branch.id, name: branch.name, commissionPercent: Number(branch.commissionPercent), income: branchIncome, expenses: branchExpenses, cashIn: branchIncome - branchExpenses, commission: branchCommission }; }); const branchCommissionTotal = branchRows.reduce((sum, branch) => sum + branch.commission, 0); const cashIn = grossRevenue + deposits;
    const netAfterCommissions = grossRevenue - expensesTotal - partnerCommission - managerCommission - branchCommissionTotal;
    const paidByBooking = new Map<string, number>(); rentalPayments.forEach(p => { if (p.bookingId) paidByBooking.set(p.bookingId, (paidByBooking.get(p.bookingId) || 0) + money(p.amount)); }); const byAsset = assets.map(asset => { const assetBookings = bookings.filter(b => b.assetId === asset.id); const days = assetBookings.reduce((s, b) => s + Math.max(0, differenceInCalendarDays(b.endDate, b.startDate)), 0); const grossIncome = assetBookings.reduce((s, b) => s + (paidByBooking.has(b.id) ? (paidByBooking.get(b.id) || 0) : Math.max(0, money(b.paidAmount) - (depositByBooking.get(b.id) || 0))), 0); const income = manager ? grossIncome * percent / 100 : grossIncome; const assetExpenses = manager ? 0 : expenses.filter(e => e.assetId === asset.id).reduce((s, e) => s + money(e.amount), 0); const blockedDays = blocks.filter(b => b.assetId === asset.id).reduce((s, b) => s + Math.max(0, differenceInCalendarDays(b.endDate, b.startDate)), 0); const monthRentalDays = assetBookings.reduce((s, b) => { const start = b.startDate < monthStart ? monthStart : b.startDate; const end = b.endDate > monthEnd ? monthEnd : b.endDate; return s + Math.max(0, differenceInCalendarDays(end, start)); }, 0); const monthBlockedDays = blocks.filter(b => b.assetId === asset.id).reduce((s, b) => { const start = b.startDate < monthStart ? monthStart : b.startDate; const end = b.endDate > monthEnd ? monthEnd : b.endDate; return s + Math.max(0, differenceInCalendarDays(end, start)); }, 0); return { assetId: asset.id, name: asset.name, status: asset.status, statusColor: asset.statusColor, currentMileage: asset.currentMileage, oilChangeMileage: asset.oilChangeMileage, variatorServiceMileage: asset.variatorServiceMileage, lastServiceDate: asset.lastServiceDate, serviceNote: asset.serviceNote, rentalDays: days, blockedDays, income, expenses: assetExpenses, profit: income - assetExpenses, bookings: assetBookings.length, monthlyIdle: Math.max(0, monthDays - monthRentalDays - monthBlockedDays) }; });
    return Response.json({ revenue: manager ? 0 : grossRevenue, deposits: manager ? 0 : deposits, expenses: manager ? 0 : expensesTotal, partnerCommission: manager ? 0 : partnerCommission, branchCommission: manager ? 0 : branchCommissionTotal, managerCommission, branches: manager ? [] : branchRows, cashIn: manager ? 0 : cashIn, net: manager ? commission : netAfterCommissions, expected: manager ? 0 : expected, commissionPercent: manager ? percent : configuredManagerPercent, commission, isManager: manager, bookings: bookings.length, rentalDays, blockedDays: blocks.reduce((s, b) => s + Math.max(0, differenceInCalendarDays(b.endDate, b.startDate)), 0), byAsset, todayReturns, todayPickups, upcomingPayments, serviceAssets });
  } catch (e) { console.error("[analytics] failed", e); return jsonError(e, 401); }
}
