import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { getAccess, jsonError } from "@/lib/api";
import { addDays, differenceInCalendarDays, startOfDay } from "date-fns";
export async function GET(request: NextRequest) {
  try {
    const { user, member } = await getAccess(request);
    const today = startOfDay(new Date()); const monthStart = new Date(today.getFullYear(), today.getMonth(), 1); const monthEnd = new Date(today.getFullYear(), today.getMonth() + 1, 1); const monthDays = differenceInCalendarDays(monthEnd, monthStart); const tomorrow = addDays(today, 1); const week = addDays(today, 7);
    const [bookings, payments, expenses, assets, blocks] = await Promise.all([
      prisma.booking.findMany({ where: { userId: user.id, status: { notIn: ["CANCELLED"] } }, include: { asset: true }, orderBy: { startDate: "asc" } }),
      prisma.payment.findMany({ where: { userId: user.id } }), prisma.expense.findMany({ where: { userId: user.id }, include: { asset: true } }), prisma.asset.findMany({ where: { userId: user.id }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }), prisma.assetBlock.findMany({ where: { userId: user.id } })
    ]);
    const money = (v: unknown) => Number(v); const percent = member ? Number(member.commissionPercent) : 0; const manager = Boolean(member);
    const rentalDays = bookings.reduce((sum, b) => sum + Math.max(0, differenceInCalendarDays(b.endDate, b.startDate)), 0); const rentalPayments = payments.filter(p => p.paymentType === "RENTAL"); const recordedBookingIds = new Set(rentalPayments.map(p => p.bookingId).filter(Boolean)); const grossRevenue = rentalPayments.reduce((s, p) => s + money(p.amount), 0) + bookings.filter(b => Number(b.paidAmount) > 0 && !recordedBookingIds.has(b.id)).reduce((s, b) => s + money(b.paidAmount), 0); const commission = grossRevenue * percent / 100; const deposits = payments.filter(p => p.paymentType === "DEPOSIT").reduce((s, p) => s + money(p.amount), 0); const expensesTotal = expenses.reduce((s, e) => s + money(e.amount), 0); const expected = bookings.reduce((s, b) => s + Math.max(0, money(b.totalPrice) - money(b.paidAmount)), 0);
    const todayReturns = bookings.filter(b => b.endDate >= today && b.endDate < tomorrow).map(b => ({ id: b.id, clientName: b.clientName, assetName: b.asset.name, time: b.endDate.toISOString(), status: b.status })); const todayPickups = bookings.filter(b => b.startDate >= today && b.startDate < tomorrow).map(b => ({ id: b.id, clientName: b.clientName, assetName: b.asset.name, time: b.startDate.toISOString(), status: b.status })); const upcomingPayments = bookings.filter(b => b.startDate >= today && b.startDate <= week && money(b.totalPrice) > money(b.paidAmount)).map(b => ({ id: b.id, clientName: b.clientName, assetName: b.asset.name, amount: Math.max(0, money(b.totalPrice) - money(b.paidAmount)), date: b.startDate.toISOString() }));
    const serviceAssets = assets.filter(a => { const mileage = a.currentMileage ?? 0; return a.status === "MAINTENANCE" || (a.serviceMileage != null && mileage >= a.serviceMileage) || (a.oilChangeMileage != null && mileage >= a.oilChangeMileage) || (a.variatorServiceMileage != null && mileage >= a.variatorServiceMileage); }).map(a => ({ id: a.id, name: a.name, status: a.status, currentMileage: a.currentMileage, serviceMileage: a.serviceMileage, oilChangeMileage: a.oilChangeMileage, variatorServiceMileage: a.variatorServiceMileage, lastServiceDate: a.lastServiceDate, serviceNote: a.serviceNote || [a.oilChangeMileage ? `масло: ${a.oilChangeMileage}` : "", a.variatorServiceMileage ? `вариатор: ${a.variatorServiceMileage}` : ""].filter(Boolean).join(" · ") }));
    const paidByBooking = new Map<string, number>(); rentalPayments.forEach(p => { if (p.bookingId) paidByBooking.set(p.bookingId, (paidByBooking.get(p.bookingId) || 0) + money(p.amount)); }); const byAsset = assets.map(asset => { const assetBookings = bookings.filter(b => b.assetId === asset.id); const days = assetBookings.reduce((s, b) => s + Math.max(0, differenceInCalendarDays(b.endDate, b.startDate)), 0); const grossIncome = assetBookings.reduce((s, b) => s + (paidByBooking.has(b.id) ? (paidByBooking.get(b.id) || 0) : money(b.paidAmount)), 0); const income = manager ? grossIncome * percent / 100 : grossIncome; const assetExpenses = manager ? 0 : expenses.filter(e => e.assetId === asset.id).reduce((s, e) => s + money(e.amount), 0); const blockedDays = blocks.filter(b => b.assetId === asset.id).reduce((s, b) => s + Math.max(0, differenceInCalendarDays(b.endDate, b.startDate)), 0); const monthRentalDays = assetBookings.reduce((s, b) => { const start = b.startDate < monthStart ? monthStart : b.startDate; const end = b.endDate > monthEnd ? monthEnd : b.endDate; return s + Math.max(0, differenceInCalendarDays(end, start)); }, 0); const monthBlockedDays = blocks.filter(b => b.assetId === asset.id).reduce((s, b) => { const start = b.startDate < monthStart ? monthStart : b.startDate; const end = b.endDate > monthEnd ? monthEnd : b.endDate; return s + Math.max(0, differenceInCalendarDays(end, start)); }, 0); return { assetId: asset.id, name: asset.name, rentalDays: days, blockedDays, income, expenses: assetExpenses, profit: income - assetExpenses, bookings: assetBookings.length, monthlyIdle: Math.max(0, monthDays - monthRentalDays - monthBlockedDays) }; });
    return Response.json({ revenue: manager ? 0 : grossRevenue, deposits: manager ? 0 : deposits, expenses: manager ? 0 : expensesTotal, net: manager ? commission : grossRevenue - expensesTotal, expected: manager ? 0 : expected, commissionPercent: percent, commission, isManager: manager, bookings: bookings.length, rentalDays, blockedDays: blocks.reduce((s, b) => s + Math.max(0, differenceInCalendarDays(b.endDate, b.startDate)), 0), byAsset, todayReturns, todayPickups, upcomingPayments, serviceAssets });
  } catch (e) { console.error("[analytics] failed", e); return jsonError(e, 401); }
}
