"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, LayoutDashboard, Plus, Search, Settings, UserRound, WalletCards } from "lucide-react";
import { addDays, format, isSameDay, startOfDay } from "date-fns";
import { ru } from "date-fns/locale";
import styles from "./page.module.css";

type Asset = { id: string; name: string; category: string; dailyRate: string | number; status: string };
type Booking = { id: string; assetId: string; clientName: string; startDate: string; endDate: string; totalPrice: string | number; paidAmount: string | number; status: string; asset?: Asset };
type Tab = "calendar" | "bookings" | "analytics" | "finance" | "profile";

const statusColors: Record<string, string> = { CONFIRMED: "blue", PENDING: "pink", PAID: "green", ACTIVE: "green", TECHNICAL: "yellow", CANCELLED: "gray" };
const days = Array.from({ length: 14 }, (_, index) => addDays(startOfDay(new Date()), index - 2));

export default function Home() {
  const [tab, setTab] = useState<Tab>("calendar");
  const [assets, setAssets] = useState<Asset[]>([]);
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [analytics, setAnalytics] = useState({ revenue: 0, deposits: 0, expenses: 0, net: 0, expected: 0, bookings: 0 });
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);

  useEffect(() => { void Promise.all([fetch("/api/assets").then(r => r.ok ? r.json() : []), fetch("/api/bookings").then(r => r.ok ? r.json() : []), fetch("/api/analytics").then(r => r.ok ? r.json() : null)]).then(([a, b, c]) => { setAssets(a); setBookings(b); if (c) setAnalytics(c); }); }, []);
  const filteredBookings = useMemo(() => bookings.filter(b => `${b.clientName} ${b.asset?.name ?? ""}`.toLowerCase().includes(search.toLowerCase())), [bookings, search]);
  const currency = (value: string | number) => `${Number(value).toLocaleString("ru-RU")} ฿`;
  const bookingStyle = (booking: Booking) => { const start = days.findIndex(d => isSameDay(d, new Date(booking.startDate))); const end = days.findIndex(d => isSameDay(d, new Date(booking.endDate))); const left = Math.max(0, start) * 86; const width = Math.max(86, (Math.max(end, start + 1) - Math.max(start, 0)) * 86); return { left, width }; };

  return <main className={styles.shell}>
    <header className={styles.header}><div><p className={styles.eyebrow}>RENTAL PLANNER</p><h1>{tab === "calendar" ? format(new Date(), "LLLL yyyy", { locale: ru }) : tab === "bookings" ? "Бронирования" : tab === "analytics" ? "Аналитика" : tab === "finance" ? "Финансы" : "Профиль"}</h1></div><button className={styles.iconButton} aria-label="Настройки"><Settings size={18} /></button></header>
    {tab === "calendar" && <section className={styles.content}><div className={styles.toolbar}><button className={styles.roundButton}><ChevronLeft size={18} /></button><button className={styles.todayButton}>Сегодня</button><button className={styles.roundButton}><ChevronRight size={18} /></button><button className={styles.primaryButton} onClick={() => setShowForm(true)}><Plus size={18} /> Бронь</button></div><div className={styles.legend}><span><i className={styles.blueDot} /> подтверждена</span><span><i className={styles.pinkDot} /> ожидает</span><span><i className={styles.greenDot} /> оплачена</span></div><div className={styles.timeline}><div className={styles.timelineHead}><div className={styles.assetHead}>Объект</div><div className={styles.days}>{days.map(day => <div className={`${styles.day} ${isSameDay(day, new Date()) ? styles.currentDay : ""}`} key={day.toISOString()}><b>{format(day, "d")}</b><small>{format(day, "EEEEE", { locale: ru })}</small></div>)}</div></div>{assets.map(asset => <div className={styles.timelineRow} key={asset.id}><div className={styles.assetCell}><b>{asset.name}</b><small>{asset.category === "SCOOTER" ? "Скутер" : "Мотоцикл"} · {currency(asset.dailyRate)}/день</small></div><div className={styles.track}>{days.map(day => <div className={styles.gridCell} key={day.toISOString()} />)}{bookings.filter(b => b.assetId === asset.id).map(booking => <button className={`${styles.bookingBar} ${styles[statusColors[booking.status] ?? "gray"]}`} style={bookingStyle(booking)} key={booking.id} onClick={() => setShowForm(true)}>{booking.clientName}</button>)}</div></div>)}{assets.length === 0 && <div className={styles.emptyState}><CalendarDays size={24} /><b>Объекты ещё не добавлены</b><span>Добавьте первый объект в профиле, чтобы увидеть шахматку.</span></div>}</div></section>}
    {tab === "bookings" && <section className={styles.content}><div className={styles.searchBox}><Search size={18} /><input placeholder="Поиск клиента или объекта" value={search} onChange={e => setSearch(e.target.value)} /></div><div className={styles.tabs}><button className={styles.activeTab}>Актуальные</button><button>Прошедшие</button><button>Архив</button></div><div className={styles.cards}>{filteredBookings.map(b => <article className={styles.bookingCard} key={b.id}><div className={styles.cardTop}><div><b>{b.clientName}</b><span>{b.asset?.name ?? "Объект"}</span></div><em className={styles[`badge_${statusColors[b.status] ?? "gray"}`]}>{b.status === "CONFIRMED" ? "Подтверждена" : b.status}</em></div><div className={styles.cardMeta}><span><Clock3 size={14} /> {format(new Date(b.startDate), "d MMM", { locale: ru })} — {format(new Date(b.endDate), "d MMM", { locale: ru })}</span><strong>{currency(b.totalPrice)}</strong></div><div className={styles.paymentLine}><span>Оплачено {currency(b.paidAmount)}</span><span>Остаток {currency(Number(b.totalPrice) - Number(b.paidAmount))}</span></div></article>)}{filteredBookings.length === 0 && <div className={styles.emptyState}><b>Бронирований нет</b><span>Создайте бронь из календаря или кнопкой «Бронь».</span></div>}</div></section>}
    {(tab === "analytics" || tab === "finance") && <section className={styles.content}><div className={styles.metricGrid}><Metric title="Выручка" value={currency(analytics.revenue)} icon={<CircleDollarSign />} accent="cyan" /><Metric title="Ожидается" value={currency(analytics.expected)} icon={<Clock3 />} accent="orange" /><Metric title="Расходы" value={currency(analytics.expenses)} icon={<WalletCards />} accent="pink" /><Metric title="Чистый результат" value={currency(analytics.net)} icon={<CircleDollarSign />} accent="green" /></div><div className={styles.panel}><div className={styles.panelTitle}><b>Сводка периода</b><span>Последние операции</span></div><div className={styles.financeRow}><span>Полученные залоги</span><strong>{currency(analytics.deposits)}</strong></div><div className={styles.financeRow}><span>Всего бронирований</span><strong>{analytics.bookings}</strong></div></div></section>}
    {tab === "profile" && <section className={styles.content}><div className={styles.profileCard}><div className={styles.avatar}><UserRound /></div><div><b>Мой автопарк</b><span>{assets.length} объектов в системе</span></div><ChevronRight size={18} /></div><div className={styles.profileCard}><div className={styles.avatar}><Settings /></div><div><b>Настройки Telegram</b><span>Часовой пояс и уведомления</span></div><ChevronRight size={18} /></div></section>}
    <nav className={styles.bottomNav}>{([ ["calendar", CalendarDays, "Календарь"], ["bookings", LayoutDashboard, "Брони"], ["analytics", CircleDollarSign, "Аналитика"], ["finance", WalletCards, "Финансы"], ["profile", UserRound, "Профиль"] ] as const).map(([key, Icon, label]) => <button key={key} className={tab === key ? styles.navActive : ""} onClick={() => setTab(key)}><Icon size={20} /><span>{label}</span></button>)}</nav>
    {showForm && <BookingModal onClose={() => setShowForm(false)} assets={assets} />}
  </main>;
}
function Metric({ title, value, icon, accent }: { title: string; value: string; icon: React.ReactNode; accent: string }) { return <div className={styles.metric}><div className={`${styles.metricIcon} ${styles[accent]}`}>{icon}</div><span>{title}</span><strong>{value}</strong></div>; }
function BookingModal({ onClose, assets }: { onClose: () => void; assets: Asset[] }) { return <div className={styles.modalBackdrop} onClick={onClose}><form className={styles.modal} onClick={e => e.stopPropagation()} onSubmit={e => { e.preventDefault(); onClose(); }}><div className={styles.modalHeader}><div><p className={styles.eyebrow}>НОВАЯ БРОНЬ</p><h2>Данные аренды</h2></div><button type="button" onClick={onClose}>×</button></div><label>Объект<select required defaultValue=""> <option value="" disabled>Выберите объект</option>{assets.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Имя клиента<input required placeholder="Например, Алексей" /></label><label>Телефон<input required placeholder="+7 900 000 00 00" /></label><div className={styles.formGrid}><label>Начало<input type="date" required /></label><label>Окончание<input type="date" required /></label></div><div className={styles.formGrid}><label>Суточная ставка<input type="number" min="0" placeholder="0" /></label><label>Предоплата<input type="number" min="0" placeholder="0" /></label></div><label>Комментарий<textarea placeholder="Дополнительные условия" /></label><button className={styles.submitButton}>Создать бронь</button></form></div>; }
