import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { verifyTelegramInitData } from "@/lib/telegram";
import { verifySession } from "@/lib/session";
export async function getAccess(request: NextRequest) { const session = verifySession(request.cookies.get("rp_session")?.value); if (session) { const user = await prisma.user.findUnique({ where: { id: session.userId } }); if (user) { const member = session.teamMemberId ? await prisma.teamMember.findFirst({ where: { id: session.teamMemberId, ownerId: user.id, active: true } }) : null; const cutoff = new Date(Date.now() - 3 * 24 * 60 * 60 * 1000);
      void prisma.auditLog.deleteMany({ where: { userId: user.id, createdAt: { lt: cutoff } } }).catch(error => console.error(JSON.stringify({ event: "audit.cleanup.error", message: error instanceof Error ? error.message : "unknown" })));
      void prisma.auditLog.create({ data: { userId: user.id, actorName: member?.name || user.companyName || "Пользователь", actorRole: member?.role || user.role, entity: "API", entityId: request.nextUrl.pathname, action: request.method, reason: "request" } }).catch(error => console.error(JSON.stringify({ event: "audit.write.error", message: error instanceof Error ? error.message : "unknown" })));
      return { user, member }; } } const initData = request.headers.get("x-telegram-init-data") || request.cookies.get("telegram_init_data")?.value; if (process.env.DEMO_MODE === "true" && !initData) return { user: await prisma.user.upsert({ where: { telegramId: BigInt(0) }, update: {}, create: { telegramId: BigInt(0), companyName: "Demo Rental" } }), member: null }; if (!initData) throw new Error("Требуется авторизация"); const tgUser = verifyTelegramInitData(initData); return { user: await prisma.user.upsert({ where: { telegramId: BigInt(tgUser.id) }, update: {}, create: { telegramId: BigInt(tgUser.id), companyName: tgUser.first_name ? `${tgUser.first_name}'s Rental` : "Rental Planner" } }), member: null }; }
export async function getUser(request: NextRequest) { return (await getAccess(request)).user; }
export function jsonError(error: unknown, status = 400) { return Response.json({ error: error instanceof Error ? error.message : "Внутренняя ошибка" }, { status }); }
